### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by KabbAmine** [KabbAmine/yowish.vim#1]
Implement a better ruby support.

Using syntax from https://github.com/vim-ruby/vim-ruby
For the screens here, I'll use @bdubaut [sample](https://gist.github.com/bdubaut/1dfe58a21c1a9659d47b).

**Comment by KabbAmine** [comment]
In the end, I didn't use highlighting groups from the vim-ruby plugin, the ones by default are enough to get a decent result.

![yowish-ruby](https://cloud.githubusercontent.com/assets/5658084/10513493/a101f53a-7350-11e5-9abb-1e014a8c294f.png)

I need feedback, for those interested (@bdubaut) please check [dev-ruby branch](https://github.com/KabbAmine/yowish.vim/tree/dev-ruby).

**Comment by bdubaut** [comment]
<img width="937" alt="screenshot" src="https://cloud.githubusercontent.com/assets/798319/10530033/c3abb49a-73e6-11e5-9f85-0963e1a567e0.png">

Looks good enough to me :)

**Comment by KabbAmine** [comment]
@bdubaut Good then :smiley: 

As an aside, I see that the background color in your screen (iterm2?) is quite lighter than the GUI one. Which colors palette are you using in your terminal?
