### ISSUE TITLE
Javascript support

### ISSUE THREAD

**Issue by KabbAmine** [KabbAmine/yowish.vim#3]
Implement a better javascript support.

Using syntax from:
- [x] https://github.com/pangloss/vim-javascript (See #2 )
- [x] https://github.com/othree/yajs.vim

**Comment by KabbAmine** [comment]
Need feedback, check [dev-js branch](https://github.com/KabbAmine/yowish.vim/tree/dev-js)

**Comment by Ajnasz** [comment]
Hi!
I like it, looks really good!

Thanks

**Comment by KabbAmine** [comment]
Thanks, good to know @Ajnasz :smiley:

I'll merge into master then.
