### ISSUE TITLE
ColorColumn support

### ISSUE THREAD

**Issue by wedgwood** [KabbAmine/yowish.vim#4]
As titled, there is no `highlight colorcolumn` specified in the colorscheme.

**Comment by KabbAmine** [comment]
I don't use this option so thanks for reporting that.

I can not decide which color suits better:

A darker/lighter background-like color?
![dark](https://cloud.githubusercontent.com/assets/5658084/10512226/845fe5bc-7347-11e5-865e-e3c7fc02d89d.png)
![light](https://cloud.githubusercontent.com/assets/5658084/10512229/8782b8be-7347-11e5-80dc-d9e29273270a.png)

Or a bright color, like the main yellow (Not _sexy_ at all....)?
![yellow](https://cloud.githubusercontent.com/assets/5658084/10512238/916976ec-7347-11e5-811f-8f6714c620d7.png)

**Comment by wedgwood** [comment]
I think the second one "lighter background-like" color is better :+1:

**Comment by KabbAmine** [comment]
@wedgwood I've forgot that the `CursorLine` group have the same color, so this is not a good idea after all :smile:
See by yourself (With `cursorcolumn` option enabled):

![ycs](https://cloud.githubusercontent.com/assets/5658084/10546033/6e732a1e-7434-11e5-981e-1b04cff21cfd.png)

The dark variant is more appropriate after thinking, we distinguish clearly the column line and its color doesn't disturb us.

**Comment by wedgwood** [comment]
@KabbAmine ok, it's up to you, I think I could accept it. :smile:

**Comment by KabbAmine** [comment]
Go for darker variant then

**Comment by wedgwood** [comment]
:ok_hand:
