### ISSUE TITLE
Setting AirLine themes trigger errors

### ISSUE THREAD

**Issue by aerosol** [KabbAmine/yowish.vim#5]
`let g:airline_theme = 'yowishu'` gives:

<img width="679" alt="screen shot 2016-01-10 at 22 24 56" src="https://cloud.githubusercontent.com/assets/173738/12224133/23683494-b7e9-11e5-8df5-b3796c178460.png">

`let g:airline_theme = 'yowish'` gives:

<img width="659" alt="screen shot 2016-01-10 at 22 25 24" src="https://cloud.githubusercontent.com/assets/173738/12224135/326a25b0-b7e9-11e5-800f-90c22c600a6d.png">

**Comment by KabbAmine** [comment]
The theme is `yowishU` with capital U.

For the 2nd screen, I can not reproduce the error.
Can you test with only yowish and airline enabled?
And if the issue remains, provide me a link to your vimrc and I'll take a look.

**UPDATE:**

Ok, forget what I've said, I've reproduced the bug.

**Comment by KabbAmine** [comment]
A careless mistake as always. It should be good now with 3d77132.

**Comment by aerosol** [comment]
Much better now, thanks :beers:
