### ISSUE TITLE
too purple

### ISSUE THREAD

**Issue by wedgwood** [KabbAmine/yowish.vim#6]
I guess `lightViolet` is too purple. what about using `['#b294bb','139']` which using in [Tomorrow-theme](https://github.com/ChrisKempson/Tomorrow-Theme)?

**Comment by KabbAmine** [comment]
The `lightViolet` used here may render not very well in terminal vim but looks good in gvim (And is not used so much).

I understand that it does not suit everyone, so the best idea for me is to give a way to customize it. I'll add a config variable or something like that to allow colors customization.

**Comment by KabbAmine** [comment]
@wedgwood Please check the [dev-config branch](https://github.com/KabbAmine/yowish.vim/tree/dev-config).
You can now use `g:yowish.colors` to define/overwrite the theme's colors, so in your case the following will do the trick:

``` vim
let g:yowish = {}
let g:yowish.colors = {'lightViolet': ['#b294bb','139']}
```

Let me know if everything works good for you, then I'll merge into master.

**Comment by wedgwood** [comment]
:+1:  using `g:yowish.colors` works fine for me. thanks!

**Comment by KabbAmine** [comment]
Good then, I'll update the README and merge into master.
Thanks for your feedback.
